### ISSUE TITLE
feedback 1

### ISSUE THREAD

**Issue by jirkasemmler** [pavlinagerslova/PROJEKT-Sluzby#1]
- [x] https://github.com/pavlinagerslova/PROJEKT-Sluzby/blob/ba9e61bb26b622c35ac288d33ab4f13163ff9280/index.html#L30 kdyz mame prazdny odkaz, tak se tam z pravidla dava `href="#"`
- [x] https://github.com/pavlinagerslova/PROJEKT-Sluzby/blob/ba9e61bb26b622c35ac288d33ab4f13163ff9280/style.css#L6 jasne, je to funkcni, ale na rekneme, ze na body bych zrovna margin nedaval a udelal bych na to nejakej vnitrni element. Proste body by z konvence melo byt po cele plose. Treba bych to cele obalil elementem main
- [x] super chvalim za znovupouziti trid!
- [x] https://github.com/pavlinagerslova/PROJEKT-Sluzby/blob/ba9e61bb26b622c35ac288d33ab4f13163ff9280/style.css#L38 to pismo (family) mas porad stejne. To bych nastavil na body nebo i na HTML. A pak v tech jednotlivych pripadech bych jen nastavoval font-size
- [x] https://github.com/pavlinagerslova/PROJEKT-Sluzby/blob/ba9e61bb26b622c35ac288d33ab4f13163ff9280/style.css#L66 , jo da se takto. Preferoval bych spise treba tridu button

**Comment by jirkasemmler** [comment]
jo a prosim ty zbytecne prazdne radky v tom HTML byt nemusi...
![image](https://user-images.githubusercontent.com/13363655/113213776-e58ebd80-9278-11eb-80d2-6420dfedfa4d.png)

**Comment by pavlinagerslova** [comment]
Díky, opraveno!
